[2022-11-27 04:15:46,698] {taskinstance.py:1026} INFO - Dependencies not met for <TaskInstance: data_ingestation_gcp_dag.local_to_gcp_task scheduled__2019-07-02T06:00:00+00:00 [queued]>, dependency 'Execution Date' FAILED: The execution date is 2019-07-02T06:00:00+00:00 but this is after the task's end date 2019-03-01T00:00:00+00:00.
[2022-11-27 04:15:46,703] {taskinstance.py:1026} INFO - Dependencies not met for <TaskInstance: data_ingestation_gcp_dag.local_to_gcp_task scheduled__2019-07-02T06:00:00+00:00 [queued]>, dependency 'Execution Date' FAILED: The execution date is 2019-07-02T06:00:00+00:00 but this is after the task's DAG's end date 2019-03-01T00:00:00+00:00.
[2022-11-27 04:15:46,722] {local_task_job.py:99} INFO - Task is not able to be run
[2022-11-27 04:50:51,566] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestation_gcp_dag.local_to_gcp_task scheduled__2019-07-02T06:00:00+00:00 [queued]>
[2022-11-27 04:50:51,625] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestation_gcp_dag.local_to_gcp_task scheduled__2019-07-02T06:00:00+00:00 [queued]>
[2022-11-27 04:50:51,627] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-11-27 04:50:51,628] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-11-27 04:50:51,629] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-11-27 04:50:51,703] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcp_task> on 2019-07-02 06:00:00+00:00
[2022-11-27 04:50:51,719] {standard_task_runner.py:52} INFO - Started process 1294 to run task
[2022-11-27 04:50:51,747] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestation_gcp_dag', 'local_to_gcp_task', 'scheduled__2019-07-02T06:00:00+00:00', '--job-id', '156', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestation_gcp.py', '--cfg-path', '/tmp/tmp9t6vb54r', '--error-file', '/tmp/tmpifwwqvhh']
[2022-11-27 04:50:51,754] {standard_task_runner.py:77} INFO - Job 156: Subtask local_to_gcp_task
[2022-11-27 04:50:52,001] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestation_gcp_dag.local_to_gcp_task scheduled__2019-07-02T06:00:00+00:00 [running]> on host 410f3484ae43
[2022-11-27 04:50:52,230] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-11-27 04:50:52,298] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestation_gcp_dag
AIRFLOW_CTX_TASK_ID=local_to_gcp_task
AIRFLOW_CTX_EXECUTION_DATE=2019-07-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-07-02T06:00:00+00:00
[2022-11-27 04:52:06,316] {python.py:175} INFO - Done. Returned value was: None
[2022-11-27 04:52:06,370] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestation_gcp_dag, task_id=local_to_gcp_task, execution_date=20190702T060000, start_date=20221127T045051, end_date=20221127T045206
[2022-11-27 04:52:06,450] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-11-27 04:52:06,554] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
