[2022-11-24 06:58:19,767] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestationDag.wget scheduled__2022-07-02T06:00:00+00:00 [queued]>
[2022-11-24 06:58:19,885] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestationDag.wget scheduled__2022-07-02T06:00:00+00:00 [queued]>
[2022-11-24 06:58:19,887] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-11-24 06:58:19,888] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-11-24 06:58:19,889] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-11-24 06:58:19,991] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): wget> on 2022-07-02 06:00:00+00:00
[2022-11-24 06:58:20,002] {standard_task_runner.py:52} INFO - Started process 2466 to run task
[2022-11-24 06:58:20,048] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestationDag', 'wget', 'scheduled__2022-07-02T06:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestation.py', '--cfg-path', '/tmp/tmpueqsbr4h', '--error-file', '/tmp/tmp512bdurq']
[2022-11-24 06:58:20,051] {standard_task_runner.py:77} INFO - Job 35: Subtask wget
[2022-11-24 06:58:20,519] {logging_mixin.py:109} INFO - Running <TaskInstance: LocalIngestationDag.wget scheduled__2022-07-02T06:00:00+00:00 [running]> on host d01293c252ef
[2022-11-24 06:58:20,816] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestationDag
AIRFLOW_CTX_TASK_ID=wget
AIRFLOW_CTX_EXECUTION_DATE=2022-07-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-02T06:00:00+00:00
[2022-11-24 06:58:20,824] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-11-24 06:58:20,830] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'wget https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-01.parquet -O /opt/***/output.csv']
[2022-11-24 06:58:20,868] {subprocess.py:85} INFO - Output:
[2022-11-24 06:58:20,965] {subprocess.py:89} INFO - bash: wget: command not found
[2022-11-24 06:58:20,967] {subprocess.py:93} INFO - Command exited with return code 127
[2022-11-24 06:58:21,025] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-11-24 06:58:21,085] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=LocalIngestationDag, task_id=wget, execution_date=20220702T060000, start_date=20221124T065819, end_date=20221124T065821
[2022-11-24 06:58:21,190] {standard_task_runner.py:92} ERROR - Failed to execute job 35 for task wget
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-11-24 06:58:21,242] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-11-24 06:58:21,430] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
