[2022-11-30 15:12:45,705] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcs_2_bq_da.gcs_2_gcs_tasks scheduled__2022-11-29T00:00:00+00:00 [queued]>
[2022-11-30 15:12:45,787] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcs_2_bq_da.gcs_2_gcs_tasks scheduled__2022-11-29T00:00:00+00:00 [queued]>
[2022-11-30 15:12:45,789] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-11-30 15:12:45,790] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-11-30 15:12:45,792] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-11-30 15:12:45,928] {taskinstance.py:1259} INFO - Executing <Task(GCSToGCSOperator): gcs_2_gcs_tasks> on 2022-11-29 00:00:00+00:00
[2022-11-30 15:12:45,950] {standard_task_runner.py:52} INFO - Started process 643 to run task
[2022-11-30 15:12:45,986] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'gcs_2_bq_da', 'gcs_2_gcs_tasks', 'scheduled__2022-11-29T00:00:00+00:00', '--job-id', '269', '--raw', '--subdir', 'DAGS_FOLDER/gcs_to_bq_yellow_dag.py', '--cfg-path', '/tmp/tmps1j32_ry', '--error-file', '/tmp/tmprv3cb0zl']
[2022-11-30 15:12:45,999] {standard_task_runner.py:77} INFO - Job 269: Subtask gcs_2_gcs_tasks
[2022-11-30 15:12:46,296] {logging_mixin.py:109} INFO - Running <TaskInstance: gcs_2_bq_da.gcs_2_gcs_tasks scheduled__2022-11-29T00:00:00+00:00 [running]> on host abdcba3d233e
[2022-11-30 15:12:46,609] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=gcs_2_bq_da
AIRFLOW_CTX_TASK_ID=gcs_2_gcs_tasks
AIRFLOW_CTX_EXECUTION_DATE=2022-11-29T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-29T00:00:00+00:00
[2022-11-30 15:12:46,618] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-11-30 15:12:46,675] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/gcs_to_gcs.py", line 268, in execute
    raise AirflowException("You can't have two empty strings inside source_object")
airflow.exceptions.AirflowException: You can't have two empty strings inside source_object
[2022-11-30 15:12:46,728] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=gcs_2_bq_da, task_id=gcs_2_gcs_tasks, execution_date=20221129T000000, start_date=20221130T151245, end_date=20221130T151246
[2022-11-30 15:12:46,808] {standard_task_runner.py:92} ERROR - Failed to execute job 269 for task gcs_2_gcs_tasks
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/gcs_to_gcs.py", line 268, in execute
    raise AirflowException("You can't have two empty strings inside source_object")
airflow.exceptions.AirflowException: You can't have two empty strings inside source_object
[2022-11-30 15:12:46,837] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-11-30 15:12:47,033] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
